### ISSUE TITLE
Remove a Peer?

### ISSUE THREAD

**Issue by jvsteiner** [libp2p/go-libp2p-host#13]
The `host` provides a `Connect()` method, but I don't see an obvious way to disconnect from a peer I no longer want to be connected to.  I also looked in the `Peerstore` interface, but haven't found a working way to do it yet.

What I've tried: 

- Cancelling the context that was passed into `Connect`
- Calling `host.Peerstore().ClearAddrs(pid)`
- Calling `host.Peerstore().SetAddrs(ID, Addrs, 10*time.Millisecond)` 

All to no avail, as I've verified the peer is still there afterwards by inspecting `host.Peerstore().Peers()`.  I feel like I'm missing something obvious - what is the usual way to handle this?

**Comment by Stebalien** [comment]
So, `peerstore.Peers()` will just return all peers we *know* something about. I don't believe we currently have method to clear out *everything* (although we probably should).

If you just want to *disconnect* from a peer, call `host.Network().ClosePeer(pid)`. However, this won't prevent it from reconnecting if it wants (we don't yet have a nice way to actually ban peers).

**Comment by jvsteiner** [comment]
this worked - i figured it was somewhat obvious - i just hadn't found the right submethod for a `host`.  IMHO, a `Connect` method would be served well with a matching `Disconnect` method, but that's my $.02 and it's easy enough for me to work with as is.

**Comment by jvsteiner** [comment]
hmm - thinking about banning - would be nice to be able to set a policy for this in application code - maybe something like the `Validator` interface from `go-floodsub`?

**Comment by Stebalien** [comment]
We do have filters for filtering out IP addresses. However, yes, a validator would be useful. Mind opening an issue in [libp2p/go-libp2p](https://github.com/libp2p/go-libp2p)?

Note: if you want a *private* network, I recommend you take a look at https://github.com/libp2p/go-libp2p-pnet/ (it uses a shared secret).

**Comment by jvsteiner** [comment]
opened over there - no need for a private network in my case, at least I don't think so at this time.
