### ISSUE TITLE
Return multiaddress with successful connect

### ISSUE THREAD

**Issue by JustinDrake** [libp2p/go-libp2p-host#2]
I'm looking for a function similar to

```
Connect(ctx context.Context, pi pstore.PeerInfo) error
```

where, if a connection is successful, the specific multiaddress within the `PeerInfo` over which a dial succeeded is returned. Is there an easy way to have that?

**Comment by hsanjuan** [comment]
Yes:

`host.Network().ConnsToPeer(peer)` gives you all the connections to a peer.

Then you can use `c.LocalMultiaddr()`.

**Comment by JustinDrake** [comment]
Thanks! I was looking for `c.RemoteMultiaddr()`.
